apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-app
  template:
    metadata:
      labels:
        app: alpine-app
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo 'Alpine is running'; sleep 30; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-app-service
spec:
  selector:
    app: alpine-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
