name: My CI pipeline

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: touch file
        run: echo "touch test.txt"

  build: 
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: build started 
        run: echo "Build started"
  
  dockerize:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: docker version
        run: docker -v
      - name: create docker image
        run: echo "docker build -t test:v1 ."
      - name: push docker image
        run: echo "docker push test:v1"

  deploy:
    needs: dockerize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube status
          kubectl get nodes

      - name: Show kubectl context and cluster info
        run: |
          kubectl config view
          kubectl config current-context
          kubectl cluster-info

      - name: Apply deployment
        run: kubectl apply -f deployment.yaml

      - name: Verify pods and services
        run: |
          kubectl get pods
          kubectl get svc
