name: My CI pipeline

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Touch file
        run: echo "touch test.txt"

  build: 
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build started 
        run: echo "Build started"

  dockerize:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker version
        run: docker -v
      - name: Create docker image
        run: echo "docker build -t test:v1 ."
      - name: Push docker image
        run: echo "docker push test:v1"

  deploy:
    needs: dockerize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check hardware resources
        run: |
          echo "CPU Information:"
          lscpu
          echo -e "\nMemory Information:"
          free -h
          echo -e "\nDisk Space:"
          df -h
          echo -e "\nSystem Information:"
          uname -a

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube status
          kubectl get nodes

      - name: Show cluster info
        run: |
          kubectl config view
          kubectl cluster-info
          kubectl version

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml

      - name: Verify deployment
        run: |
          kubectl get pods
          kubectl get svc
